markone = int(input("Please enter your first mark: \n"))
marktwo = int(input("Please enter your second mark: \n"))
markthree = int(input("Please enter your third mark: \n"))
markfour = int(input("Please enter your forth mark: \n"))
totalmark = int((markone + marktwo + markthree + markfour) /4)
print("Your mark is", totalmark)
